version: "2"

services:

  # https://github.com/djfarrelly/MailDev/blob/master/docs/docker.md#docker-compose
  maildev:
    image: djfarrelly/maildev:1.0.0
    ports:
      - "1080:80"
    networks:
      - mail
    restart: always

  postgres:
    image: postgres:9.5
    volumes:
      # Create bind mount for data so that it will persist between test sessions
      - ./db_data:/var/lib/postgresql/data
    networks:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      # Work around bind mount directory having a README.md file within by
      # specifying a subdirectory of that path as where data should be stored
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  cachet:
    build:
      context: .
      args:
        - cachet_ver=master
    ports:
      - 80:8000
    networks:
      - db
      - mail
      - web
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - DEBUG=false
    depends_on:
      - postgres
    restart: on-failure

networks:
  db:
  web:
  mail:
